2024-07-20 16:45:13,189 INFO    StreamThr :24870 [internal.py:wandb_internal():85] W&B internal server running at pid: 24870, started at: 2024-07-20 16:45:13.188521
2024-07-20 16:45:13,189 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status
2024-07-20 16:45:13,196 INFO    WriterThread:24870 [datastore.py:open_for_write():87] open: /Users/zend/Desktop/faster-pytorch/01Wandb/wandb/run-20240720_164513-axrv0wdp/run-axrv0wdp.wandb
2024-07-20 16:45:13,196 DEBUG   SenderThread:24870 [sender.py:send():379] send: header
2024-07-20 16:45:13,208 DEBUG   SenderThread:24870 [sender.py:send():379] send: run
2024-07-20 16:45:18,247 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:45:23,285 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:45:28,306 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:45:31,574 INFO    SenderThread:24870 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/connectionpool.py", line 775, in urlopen
    self._prepare_proxy(conn)
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1044, in _prepare_proxy
    conn.connect()
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/util/util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/connectionpool.py", line 775, in urlopen
    self._prepare_proxy(conn)
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1044, in _prepare_proxy
    conn.connect()
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/connection.py", line 652, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/connection.py", line 805, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
               ^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/ssl.py", line 1042, in _create
    self.do_handshake()
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/requests/adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-07-20 16:45:33,330 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:45:38,348 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:45:43,371 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:45:48,393 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:45:53,417 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:45:58,441 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:46:03,459 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:46:08,487 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:46:13,519 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:46:18,543 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:46:23,564 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:46:28,593 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:46:33,701 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:46:38,731 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:46:43,756 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: cancel
2024-07-20 16:46:43,756 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: cancel
2024-07-20 16:46:43,756 DEBUG   SenderThread:24870 [sender.py:send():388] Record cancelled: run
2024-07-20 16:46:43,757 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:46:48,780 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:46:49,043 INFO    StreamThr :24870 [internal.py:wandb_internal():85] W&B internal server running at pid: 24870, started at: 2024-07-20 16:46:49.042757
2024-07-20 16:46:49,044 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status
2024-07-20 16:46:49,051 INFO    WriterThread:24870 [datastore.py:open_for_write():87] open: /Users/zend/Desktop/faster-pytorch/01Wandb/wandb/run-20240720_164649-k44l8zqf/run-k44l8zqf.wandb
2024-07-20 16:46:49,051 DEBUG   SenderThread:24870 [sender.py:send():379] send: header
2024-07-20 16:46:49,052 DEBUG   SenderThread:24870 [sender.py:send():379] send: run
2024-07-20 16:46:53,802 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:46:54,082 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:46:56,591 INFO    SenderThread:24870 [dir_watcher.py:__init__():211] watching files in: /Users/zend/Desktop/faster-pytorch/01Wandb/wandb/run-20240720_164649-k44l8zqf/files
2024-07-20 16:46:56,591 INFO    SenderThread:24870 [sender.py:_start_run_threads():1188] run started: k44l8zqf with start time 1721465209.042585
2024-07-20 16:46:56,591 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:46:58,825 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:46:59,108 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:01,611 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:03,846 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:04,131 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:06,627 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:08,865 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:09,161 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:11,645 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:13,886 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:14,183 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:16,668 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:18,905 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:19,210 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:21,691 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:23,920 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:24,239 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:26,711 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:28,945 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:29,258 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:31,730 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:33,964 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:34,284 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:36,753 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:38,982 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:39,312 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:41,769 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:43,999 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:44,346 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:46,784 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:49,018 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:49,369 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:51,804 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:54,037 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:54,394 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:47:56,824 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:59,058 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:47:59,421 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:48:01,846 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:04,077 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:04,450 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:48:06,861 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:09,091 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:09,476 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:48:11,880 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:14,123 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:14,500 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:48:16,893 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:19,133 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:19,524 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: cancel
2024-07-20 16:48:19,524 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: cancel
2024-07-20 16:48:21,923 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:24,153 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:26,946 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:29,172 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:31,144 INFO    StreamThr :24870 [internal.py:wandb_internal():85] W&B internal server running at pid: 24870, started at: 2024-07-20 16:48:31.144223
2024-07-20 16:48:31,146 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status
2024-07-20 16:48:31,151 INFO    WriterThread:24870 [datastore.py:open_for_write():87] open: /Users/zend/Desktop/faster-pytorch/01Wandb/wandb/run-20240720_164831-d9zrywgv/run-d9zrywgv.wandb
2024-07-20 16:48:31,152 DEBUG   SenderThread:24870 [sender.py:send():379] send: header
2024-07-20 16:48:31,152 DEBUG   SenderThread:24870 [sender.py:send():379] send: run
2024-07-20 16:48:31,965 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:33,468 INFO    SenderThread:24870 [dir_watcher.py:__init__():211] watching files in: /Users/zend/Desktop/faster-pytorch/01Wandb/wandb/run-20240720_164831-d9zrywgv/files
2024-07-20 16:48:33,469 INFO    SenderThread:24870 [sender.py:_start_run_threads():1188] run started: d9zrywgv with start time 1721465311.143998
2024-07-20 16:48:34,197 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:36,176 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:48:36,483 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:36,987 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:39,209 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:41,199 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: keepalive
2024-07-20 16:48:41,497 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:42,007 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
2024-07-20 16:48:44,257 DEBUG   HandlerThread:24870 [handler.py:handle_request():158] handle_request: status_report
