2024-07-20 16:46:49,040 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-07-20 16:46:49,040 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Configure stats pid to 23323
2024-07-20 16:46:49,040 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Loading settings from /Users/zend/.config/wandb/settings
2024-07-20 16:46:49,040 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Loading settings from /Users/zend/Desktop/faster-pytorch/01Wandb/wandb/settings
2024-07-20 16:46:49,041 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-20 16:46:49,041 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-20 16:46:49,041 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-07-20 16:46:49,041 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-20 16:46:49,041 INFO    MainThread:23323 [wandb_init.py:_log_setup():529] Logging user logs to /Users/zend/Desktop/faster-pytorch/01Wandb/wandb/run-20240720_164649-k44l8zqf/logs/debug.log
2024-07-20 16:46:49,041 INFO    MainThread:23323 [wandb_init.py:_log_setup():530] Logging internal logs to /Users/zend/Desktop/faster-pytorch/01Wandb/wandb/run-20240720_164649-k44l8zqf/logs/debug-internal.log
2024-07-20 16:46:49,041 INFO    MainThread:23323 [wandb_init.py:init():569] calling init triggers
2024-07-20 16:46:49,041 INFO    MainThread:23323 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {'lr': 0.0001, 'epoch': 3, 'batch_size': 64}
2024-07-20 16:46:49,041 INFO    MainThread:23323 [wandb_init.py:init():619] starting backend
2024-07-20 16:46:49,041 INFO    MainThread:23323 [wandb_init.py:init():623] setting up manager
2024-07-20 16:46:49,042 INFO    MainThread:23323 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-07-20 16:46:49,042 INFO    MainThread:23323 [wandb_init.py:init():631] backend started and connected
2024-07-20 16:46:49,050 INFO    MainThread:23323 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-07-20 16:46:49,050 INFO    MainThread:23323 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-07-20 16:46:49,051 INFO    MainThread:23323 [wandb_init.py:init():720] updated telemetry
2024-07-20 16:46:49,051 INFO    MainThread:23323 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-07-20 16:48:19,524 ERROR   MainThread:23323 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-07-20 16:48:19,525 ERROR   MainThread:23323 [wandb_init.py:init():1191] error in wandb.init()
Traceback (most recent call last):
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1181, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/zend/Desktop/faster-pytorch/.pixi/envs/default/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-07-20 16:48:31,135 INFO    MainThread:23323 [wandb_settings.py:_apply_login():1935] Applying login settings: {}
2024-07-20 16:48:31,140 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-07-20 16:48:31,140 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Configure stats pid to 23323
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Loading settings from /Users/zend/.config/wandb/settings
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Loading settings from /Users/zend/Desktop/faster-pytorch/01Wandb/wandb/settings
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_init.py:_log_setup():529] Logging user logs to /Users/zend/Desktop/faster-pytorch/01Wandb/wandb/run-20240720_164831-d9zrywgv/logs/debug.log
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_init.py:_log_setup():530] Logging internal logs to /Users/zend/Desktop/faster-pytorch/01Wandb/wandb/run-20240720_164831-d9zrywgv/logs/debug-internal.log
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_init.py:init():569] calling init triggers
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {'lr': 0.0001, 'epoch': 3, 'batch_size': 64}
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_init.py:init():619] starting backend
2024-07-20 16:48:31,141 INFO    MainThread:23323 [wandb_init.py:init():623] setting up manager
2024-07-20 16:48:31,143 INFO    MainThread:23323 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-07-20 16:48:31,143 INFO    MainThread:23323 [wandb_init.py:init():631] backend started and connected
2024-07-20 16:48:31,150 INFO    MainThread:23323 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-07-20 16:48:31,150 INFO    MainThread:23323 [wandb_run.py:_label_probe_notebook():1344] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-07-20 16:48:31,150 INFO    MainThread:23323 [wandb_init.py:init():720] updated telemetry
2024-07-20 16:48:31,151 INFO    MainThread:23323 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
